import Head from 'next/head'
import Image from 'next/image'
import Cards from '@/components/cards'
import Slider from '@/components/slider'
import styles from '@/styles/Home.module.css'
import content from '../data.json';

export default function Home() {
  return (
    <>
      <Head>
        <title>nextJS Landingpage </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div>
            <Image
              className={styles.logo}
              src="/logo.svg"
              alt="{content.title}"
              width={280}
              height={280}
              priority
            />

            <h1>
              {content.title}
            </h1>
          </div>
        </div>

        <Cards content={content.posts}/>
        <Slider content={content.slides} />
      </main>
    </>
  )
}
